FROM python:3.13-slim-bookworm@sha256:6544e0e002b40ae0f59bc3618b07c1e48064c4faed3a15ae2fbd2e8f663e8283

WORKDIR /app

ARG DBUS2MQTT_VERSION=latest

RUN pip install --no-cache-dir dbus2mqtt=="$DBUS2MQTT_VERSION"

ENTRYPOINT ["python", "-m", "dbus2mqtt"]

# show help message by default
CMD ["--help"]
