FROM python:3.13-slim-bookworm@sha256:4c2cf9917bd1cbacc5e9b07320025bdb7cdf2df7b0ceaccb55e9dd7e30987419

WORKDIR /app

ARG DBUS2MQTT_VERSION=latest

RUN pip install --no-cache-dir dbus2mqtt=="$DBUS2MQTT_VERSION"

ENTRYPOINT ["python", "-m", "dbus2mqtt"]

# show help message by default
CMD ["--help"]
