FROM python:3.13-slim-bookworm@sha256:6f79e7a10bb7d0b0a50534a70ebc78823f941fba26143ecd7e6c5dca9d7d7e8a

WORKDIR /app

ARG DBUS2MQTT_VERSION=latest

RUN pip install --no-cache-dir dbus2mqtt=="$DBUS2MQTT_VERSION"

ENTRYPOINT ["python", "-m", "dbus2mqtt"]

# show help message by default
CMD ["--help"]
